class ESTADOS:
    ACTIVO = 1
    INACTIVO = 2

class ROLES:
    ADMIN = 1
    OPERADOR = 2

class TIPOS_EVENTO:
    LOGIN = 1
    LOGIN_FALLIDO = 2
    USUARIO_AGREGAR = 3
    USUARIO_MODIFICAR = 4
    USUARIO_DESHABILITAR = 5
    PROYECTO_AGREGAR = 6
    PROYECTO_MODIFICAR = 7
    PROYECTO_DESHABILITAR = 8
    SERVIDOR_AGREGAR = 9
    SERVIDOR_MODIFICAR = 10
    SERVIDOR_DESHABILITAR = 11
    SERVIDOR_ACCESO = 12